config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins
  #Routes for users
  namespace :api do
    namespace :v1 do
      resources :users
    end
  end
  #Routes for authentication
  namespace :api do
    namespace :v1 do
      resources :authentication
    end
  end
  #Routes for rooms
  namespace :api do
    namespace :v1 do
      resources :rooms
    end
  end
  #Routes for goals
  namespace :api do
    namespace :v1 do
      resources :goals
    end
  end
  #Routes for styles
  namespace :api do
    namespace :v1 do
      resources :styles
    end
  end
  #Routes for user_requirement_styles
  namespace :api do
    namespace :v1 do
      resources :user_requirement_styles
    end
  end
  #Routes for user_requirements
  namespace :api do
    namespace :v1 do
      resources :user_requirements
    end
  end
  #Routes for user_requirement_goals
  namespace :api do
    namespace :v1 do
      resources :user_requirement_goals
    end
  end
  #Routes for user_requirements in admin panel
  namespace :admin do
    resources :user_requirements
  end
  devise_scope :admin do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

app/models/user_requirement.rb
class UserRequirement < ApplicationRecord
	has_many :user_requirement_styles
	has_many :user_requirement_goals
  accepts_nested_attributes_for :user_requirement_styles, allow_destroy: true
  accepts_nested_attributes_for :user_requirement_goals, allow_destroy: true
  belongs_to :user, inverse_of: :user_requirements
  belongs_to :room, optional: true

  #get user email
  def user_email
    self.user.email
  end
  
  #get goal content
  def goal_content
    self.user_requirement_goals.pluck(:content).join(", ")
  end
  
  #get style image 
  def style_image
    @x = []
    self.user_requirement_styles.each do |s|
      @x.push(%{<img src="/assets/#{s.image}.png"><div style="text-align:center;width: 177px;">#{s.content}</div>})
    end
    return @x.split(",").join(" ").html_safe    
  end
  
  #get room image
  def room_image
    %{<img src="/assets/#{self.room.image}.png"><div style="text-align:center;width: 356px;">#{self.room.content}</div>}.html_safe
  end

  # Display user_requirement details in admin panel
  rails_admin do
    field :id
    field :user do 
      pretty_value do
        value.try(:email)
      end
    end
    show do
      field :user_email 
      field :furniture
      field :room_image
      field :goal_content
      field :style_image
    end  
  end
end

app/controllers/admin/user_requirements_controller.rb
class Admin::UserRequirementsController < ApplicationController
  #Get all user_requirements 
  def index
    @user_requirements = UserRequirement.paginate(:page => params[:page], :per_page => 10)
  end

  # Get a user_requirement by id
  def show
    @user_requirement = UserRequirement.find(params[:id])
  end

  # GET method for the new user_requirement  
  def new   
    @user_requirement = UserRequirement.new
  end   
  
  # POST method for processing user_requirement 
  def create 
    @user_requirement = UserRequirement.new(user_requirement_params)
    if @user_requirement.save
      render json: @user_requirement, status: :created    
    else   
      render json: @user_requirement.errors, status: :unprocessable_entity
    end   
  end

  # GET method for editing a user_requirement based on id
  def edit 
    @user_requirement = UserRequirement.find(params[:id]) 
    render json: @user_requirement
  end 

  # PUT method for updating in database a user_requirement based on id 
  def update   
    @user_requirement = UserRequirement.find(params[:id])
    if @user_requirement.update_attributes(user_requirement_params)   
      render json: @user_requirement, status: :updated
    else     
      render json: @user_requirement.errors, status: :unprocessable_entity   
    end   
  end   

  # DELETE method for deleting a user_requirement from database based on id
  def destroy   
    @user_requirement = UserRequirement.find(params[:id]) 
    @user_requirement.delete
  end  

  private

  # we used strong parameters for the validation of params 
  def user_requirement_params   
    params.require(:user_requirement).permit(:user_id, :room_id, :furniture, user_requirement_styles_attributes: [:image, :content], user_requirement_goals_attributes: [:content] )   
  end  
end

app/controllers/api/v1/user_requirements_controller.rb
class Api::V1::UserRequirementsController < ApplicationController
  #Get all user_requirements 
  def index
    @user_requirements = UserRequirement.all
    render json: @user_requirements, status: :ok
  end

   # Get a user_requirement by id
  def show
    @user_requirement = UserRequirement.find(params[:id])
    render json: @user_requirement
  end

  # GET method for the new user_requirement 
  def new   
    @user_requirement = UserRequirement.new
  end   
   
  # POST method for processing user_requirement
  def create 
    @user_requirement = UserRequirement.new(user_requirement_params)
    if @user_requirement.save
      render json: @user_requirement, status: :created    
    else   
      render json: @user_requirement.errors, status: :unprocessable_entity
    end   
  end

  
  private

  # we used strong parameters for the validation of params 
  def user_requirement_params   
    params.require(:user_requirement).permit(:user_id, :room_id, :furniture, user_requirement_styles_attributes: [:image, :content], user_requirement_goals_attributes: [:content] )   
  end  

end

app/helpers/user_requirements_helper.rb
module UserRequirementsHelper
end

app/views/admin/user_requirements/create.html.erb
<h1>UserRequirements#create</h1>
<p>Find me in app/views/user_requirements/create.html.erb</p>

app/views/admin/user_requirements/destroy.html.erb
<h1>UserRequirements#destroy</h1>
<p>Find me in app/views/user_requirements/destroy.html.erb</p>

app/views/admin/user_requirements/index.html.erb
<!-- Customers list -->
<div class="user-list">
  <div class="container container-color">
    <div style="text-align: right;">
      <%= link_to 'Log out', destroy_admin_session_path, method: :delete, :class => 'btn btn-danger logout-top' %>
    </div> 
    <h4 class="customers">CUSTOMERS</h4> 
    <table border="2" class="table table-background"> 
      <thead>   
        <tr>   
    		  <th>Id</th>   
          <th>Email</th>   
          <th>Date</th>   
          <th>Action</th>   
      	</tr>   
    	</thead>   	
    	<tbody>   
        <% @user_requirements.each do |ur| %>
          <tr>
    	      <td><%= ur.id %></td>   
    	      <td><%= ur.user.email %></td>
            <td><%= ur.created_at.strftime("%d/%m/%Y") %></td>
    	      <td><%= link_to 'VIEW', admin_user_requirement_path(ur), :class => "btn btn-success view-btn" %></td>
       		</tr>
        <% end %>
      </tbody>
    </table>

    <div class="page"><%= will_paginate(@user_requirements, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %></div>       
  </div>
</div>   

app/views/admin/user_requirements/new.html.erb
<h1>UserRequirements#new</h1>
<p>Find me in app/views/user_requirements/new.html.erb</p>

app/views/admin/user_requirements/show.html.erb
<!--display user_requirements based on user id -->
<div style="margin-top: 25px;">
	<div class="container">
		<div style="text-align: right;">
			<%= link_to 'Back', admin_user_requirements_path, :class => 'btn btn-info' %>
		</div>
		<h4 class="requirement">Requirements</h4>	
		<div><span class="customer-email">CUSTOMER:</span> <%= @user_requirement.user.email %></div>
		<div>
			<div class="room">ROOM DESIGN</div>
			<div class="room-content">
				<div><%= image_tag (@user_requirement.room.image), class: "image" %><br><span class="room-content"><%= @user_requirement.room.content %></span></div>
			</div>	
		</div>
		<div class="room">RE-DESIGN</div>
		<% @user_requirement.user_requirement_goals.each do |g| %>
			<ul>	
				<li><%= g.content %></li>
			</ul>
		<% end %>
		<div class="room">FURNITURE</div>
		<div><%= image_tag (@user_requirement.furniture), class: "image" %></div>
		<div class="room">STYLES</div>
		<div class="styles">
			<% @user_requirement.user_requirement_styles.each do |s| %>
				<div class="style-img"><%= image_tag (s.image) %><br><span class="style-content"><%= s.content %></span></div>
			<% end %>
		</div>	
	</div>
</div>